-- Tạo bảng Inventory (Tồn kho)
CREATE TABLE inventory (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    quantity NUMBER DEFAULT 0,
    min_stock_level NUMBER DEFAULT 10,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventory_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT uk_inventory_product UNIQUE (product_id)
);

-- Tạo bảng Inventory Transactions (Lịch sử giao dịch kho)
CREATE TABLE inventory_transactions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    transaction_type VARCHAR2(20) NOT NULL CHECK (transaction_type IN ('IMPORT', 'EXPORT', 'ADJUSTMENT')),
    quantity NUMBER NOT NULL,
    note VARCHAR2(500),
    created_by VARCHAR2(100),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_transaction_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- Tạo index để tăng tốc độ truy vấn
-- Lưu ý: product_id đã có index tự động từ UNIQUE constraint, không cần tạo lại
CREATE INDEX idx_inventory_low_stock ON inventory(quantity, min_stock_level);
CREATE INDEX idx_transaction_product ON inventory_transactions(product_id);
CREATE INDEX idx_transaction_date ON inventory_transactions(created_date DESC);

-- Thêm dữ liệu mẫu cho inventory (tùy chọn)
-- LƯU Ý: Chỉ chạy phần này sau khi đã có sản phẩm trong bảng products
-- Hoặc thay đổi product_id thành ID sản phẩm thực tế trong hệ thống của bạn

-- Kiểm tra ID sản phẩm hiện có trước khi chạy:
-- SELECT id, name FROM products ORDER BY id;

-- Ví dụ: Thêm tồn kho cho các sản phẩm đầu tiên (uncomment và sửa ID nếu cần)
/*
INSERT INTO inventory (product_id, quantity, min_stock_level) 
SELECT id, 50, 10 FROM products WHERE ROWNUM <= 1;

INSERT INTO inventory (product_id, quantity, min_stock_level) 
SELECT id, 30, 10 FROM products WHERE ROWNUM <= 1 AND id NOT IN (SELECT product_id FROM inventory);

-- Thêm giao dịch mẫu
INSERT INTO inventory_transactions (product_id, transaction_type, quantity, note, created_by) 
SELECT product_id, 'IMPORT', 50, 'Nhập kho đầu tiên', 'admin' 
FROM inventory WHERE ROWNUM <= 1;
*/

COMMIT;
